// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUiGzoTfWadlL0q41Zv7RAwXCZ7LbHct0',
    appId: '1:108475528200:web:d87ac4c6aca2c8a4610dbd',
    messagingSenderId: '108475528200',
    projectId: 'ajob-app',
    authDomain: 'ajob-app.firebaseapp.com',
    storageBucket: 'ajob-app.appspot.com',
    measurementId: 'G-EWQKJ7KQKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_Im6JJ7NAXsxk1hM4PBBa7Gk1IXdwr4',
    appId: '1:108475528200:android:33a7ec5804d65558610dbd',
    messagingSenderId: '108475528200',
    projectId: 'ajob-app',
    storageBucket: 'ajob-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjK-hjBoL5KPVJnkvCgxMVLtUTgrqUZA0',
    appId: '1:108475528200:ios:d3d949d9e37cac5b610dbd',
    messagingSenderId: '108475528200',
    projectId: 'ajob-app',
    storageBucket: 'ajob-app.appspot.com',
    iosClientId: '108475528200-2m0kqlnkq85msnfej9m4dcug355dbdpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.achat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjK-hjBoL5KPVJnkvCgxMVLtUTgrqUZA0',
    appId: '1:108475528200:ios:d3d949d9e37cac5b610dbd',
    messagingSenderId: '108475528200',
    projectId: 'ajob-app',
    storageBucket: 'ajob-app.appspot.com',
    iosClientId: '108475528200-2m0kqlnkq85msnfej9m4dcug355dbdpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.achat',
  );
}
